### PR TITLE
Add run on repl.it badge to README

### PR DESCRIPTION
**Pull request by nraikm**
This pull request configures this repository to be run on Repl.it.It adds a `.replit` configuration file and a Repl.it badge to the `README`. This will allow viewers of the repository to click the run on Repl.it button and be able to use ddgr inside the Repl.it environment.
You can read more about running repos on Repl.it [here](https://docs.repl.it/repls/dot-replit), or view the Repl [here](https://repl.it/@Mosrod/Watson).

### CODE REVIEW

**Comment by k4nar** [comment]
Why not, but it doesn't seem to be working out of the box. I got it working by doing `pip install td-watson`, but I'm not sure that's the intent of repl.it.

**Comment by Mosrod** [comment]
You need to click the run button and it should be installed automatically 😁.

**Comment by jmaupetit** [comment]
Not sure to see the point of using repl.it with Watson. Can you explain what are you trying to solve using such service?

**Comment by Mosrod** [comment]
The point of using Repl.it with Watson is for new users to be able to quickly experiment with Watson using the command line on a new and quickly set up environment instead of having to

**Pull request closed without merging**
